import { ComponentConfig, CategoryConfig } from '@/types';
import {
  AppstoreOutlined,
  BorderOutlined,
  CheckSquareOutlined,
  FormOutlined,
  FileTextOutlined,
  PictureOutlined,
  SyncOutlined,
  CalendarOutlined,
  UploadOutlined,
  CreditCardOutlined,
  SplitCellsOutlined,
  ProfileOutlined,
  FundOutlined,
  AlertOutlined,
  MessageOutlined,
  NotificationOutlined,
  LoadingOutlined,
  TagOutlined,
  TableOutlined,
  MenuFoldOutlined,
  InfoCircleOutlined,
  RocketOutlined,
  CodeOutlined,
  OrderedListOutlined,
  UnorderedListOutlined,
  LineOutlined,
  // 新增图标
  NumberOutlined,
  ClockCircleOutlined,
  DownOutlined,
  SettingOutlined,
} from '@ant-design/icons';

/**
 * 组件分类配置
 */
export const CATEGORIES: CategoryConfig[] = [
  { key: 'basic', name: '基础组件', order: 1 },
  { key: 'form', name: '表单组件', order: 2 },
  { key: 'layout', name: '布局组件', order: 3 },
  { key: 'display', name: '展示组件', order: 4 },
  { key: 'feedback', name: '反馈组件', order: 5 },
  { key: 'html', name: '原生HTML', order: 6 },
];

/**
 * 预设组件配置
 */
export const PRESET_COMPONENTS: ComponentConfig[] = [
  // ============ 基础组件 ============
  {
    type: 'Button',
    name: '按钮',
    icon: <AppstoreOutlined />,
    category: 'basic',
    defaultProps: {
      children: '按钮',
      type: 'primary',
      size: 'middle',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '按钮文字',
        type: 'string',
        defaultValue: '按钮',
        group: '基础',
      },
      {
        name: 'type',
        label: '按钮类型',
        type: 'select',
        defaultValue: 'primary',
        options: [
          { label: '主要按钮', value: 'primary' },
          { label: '默认按钮', value: 'default' },
          { label: '虚线按钮', value: 'dashed' },
          { label: '文字按钮', value: 'text' },
          { label: '链接按钮', value: 'link' },
        ],
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'block',
        label: '宽度撑满',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Input',
    name: '输入框',
    icon: <FormOutlined />,
    category: 'basic',
    defaultProps: {
      placeholder: '请输入',
      size: 'middle',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请输入',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'allowClear',
        label: '允许清除',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'Select',
    name: '下拉选择',
    icon: <BorderOutlined />,
    category: 'basic',
    defaultProps: {
      placeholder: '请选择',
      size: 'middle',
      options: [
        { label: '选项一', value: '1' },
        { label: '选项二', value: '2' },
      ],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请选择',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'allowClear',
        label: '允许清除',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  // ============ 表单组件 ============
  {
    type: 'Checkbox',
    name: '复选框',
    icon: <CheckSquareOutlined />,
    category: 'form',
    defaultProps: {
      children: '复选框',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '标签文字',
        type: 'string',
        defaultValue: '复选框',
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Switch',
    name: '开关',
    icon: <SyncOutlined />,
    category: 'form',
    defaultProps: {
      checkedChildren: '开',
      unCheckedChildren: '关',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'checkedChildren',
        label: '选中文字',
        type: 'string',
        defaultValue: '开',
        group: '基础',
      },
      {
        name: 'unCheckedChildren',
        label: '未选中文字',
        type: 'string',
        defaultValue: '关',
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'DatePicker',
    name: '日期选择',
    icon: <CalendarOutlined />,
    category: 'form',
    defaultProps: {
      placeholder: '请选择日期',
      size: 'middle',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请选择日期',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'Upload',
    name: '上传',
    icon: <UploadOutlined />,
    category: 'form',
    defaultProps: {},
    defaultStyle: {},
    propSchema: [
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  // ============ 布局组件 ============
  {
    type: 'Card',
    name: '卡片',
    icon: <CreditCardOutlined />,
    category: 'layout',
    defaultProps: {
      title: '卡片标题',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '卡片标题',
        group: '基础',
      },
      {
        name: 'bordered',
        label: '显示边框',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'hoverable',
        label: '悬停效果',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 300, height: 200 },
  },

  {
    type: 'Divider',
    name: '分割线',
    icon: <SplitCellsOutlined />,
    category: 'layout',
    defaultProps: {
      orientation: 'center',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'orientation',
        label: '文字位置',
        type: 'select',
        defaultValue: 'center',
        options: [
          { label: '居左', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '居右', value: 'right' },
        ],
        group: '基础',
      },
      {
        name: 'dashed',
        label: '虚线',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  // ============ 展示组件 ============
  {
    type: 'Typography.Text',
    name: '文本',
    icon: <FileTextOutlined />,
    category: 'display',
    defaultProps: {
      children: '这是一段文本',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: '这是一段文本',
        group: '基础',
      },
      {
        name: 'type',
        label: '文本类型',
        type: 'select',
        defaultValue: undefined,
        options: [
          { label: '默认', value: undefined },
          { label: '次要', value: 'secondary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
        ],
        group: '基础',
      },
      {
        name: 'bold',
        label: '加粗',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Image',
    name: '图片',
    icon: <PictureOutlined />,
    category: 'display',
    defaultProps: {
      src: 'https://via.placeholder.com/200x150',
      alt: '图片',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'src',
        label: '图片地址',
        type: 'string',
        defaultValue: 'https://via.placeholder.com/200x150',
        group: '基础',
      },
      {
        name: 'alt',
        label: '替代文本',
        type: 'string',
        defaultValue: '图片',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 150 },
  },

  {
    type: 'Statistic',
    name: '统计数值',
    icon: <FundOutlined />,
    category: 'display',
    defaultProps: {
      title: '活跃用户',
      value: 112893,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '活跃用户',
        group: '基础',
      },
      {
        name: 'value',
        label: '数值',
        type: 'number',
        defaultValue: 112893,
        group: '基础',
      },
      {
        name: 'prefix',
        label: '前缀',
        type: 'string',
        defaultValue: '',
        group: '基础',
      },
      {
        name: 'suffix',
        label: '后缀',
        type: 'string',
        defaultValue: '',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Descriptions',
    name: '描述列表',
    icon: <ProfileOutlined />,
    category: 'display',
    defaultProps: {
      title: '描述列表',
      items: [
        { label: '姓名', children: '张三' },
        { label: '年龄', children: '25' },
        { label: '地址', children: '北京市朝阳区' },
      ],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '描述列表',
        group: '基础',
      },
      {
        name: 'bordered',
        label: '显示边框',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'column',
        label: '列数',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 4,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  // ============ 反馈组件 ============
  {
    type: 'Modal',
    name: '对话框',
    icon: <AlertOutlined />,
    category: 'feedback',
    defaultProps: {
      title: '对话框标题',
      open: true,
      children: '对话框内容',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '对话框标题',
        group: '基础',
      },
      {
        name: 'open',
        label: '是否显示',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'width',
        label: '宽度',
        type: 'number',
        defaultValue: 520,
        group: '基础',
      },
      {
        name: 'centered',
        label: '垂直居中',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 520, height: 'auto' },
    requiresOverlap: true,
    dragPreviewSize: { width: 50, height: 50 },
  },

  {
    type: 'Drawer',
    name: '抽屉',
    icon: <MenuFoldOutlined />,
    category: 'feedback',
    defaultProps: {
      title: '抽屉标题',
      open: true,
      placement: 'right',
      width: 378,
      children: '抽屉内容',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '抽屉标题',
        group: '基础',
      },
      {
        name: 'open',
        label: '是否显示',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'placement',
        label: '方向',
        type: 'select',
        defaultValue: 'right',
        options: [
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
          { label: '顶部', value: 'top' },
          { label: '底部', value: 'bottom' },
        ],
        group: '基础',
      },
      {
        name: 'width',
        label: '宽度',
        type: 'number',
        defaultValue: 378,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 378, height: 300 },
    requiresOverlap: true,
    dragPreviewSize: { width: 50, height: 50 },
  },

  {
    type: 'Message',
    name: '全局提示',
    icon: <MessageOutlined />,
    category: 'feedback',
    defaultProps: {
      type: 'info',
      content: '这是一条提示信息',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'info',
        options: [
          { label: '信息', value: 'info' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '错误', value: 'error' },
          { label: '加载中', value: 'loading' },
        ],
        group: '基础',
      },
      {
        name: 'content',
        label: '内容',
        type: 'string',
        defaultValue: '这是一条提示信息',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Notification',
    name: '通知提醒',
    icon: <NotificationOutlined />,
    category: 'feedback',
    defaultProps: {
      type: 'info',
      message: '通知标题',
      description: '这是通知的详细描述内容',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'info',
        options: [
          { label: '信息', value: 'info' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '错误', value: 'error' },
        ],
        group: '基础',
      },
      {
        name: 'message',
        label: '标题',
        type: 'string',
        defaultValue: '通知标题',
        group: '基础',
      },
      {
        name: 'description',
        label: '描述',
        type: 'string',
        defaultValue: '这是通知的详细描述内容',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 384, height: 'auto' },
  },

  {
    type: 'Alert',
    name: '警告提示',
    icon: <InfoCircleOutlined />,
    category: 'feedback',
    defaultProps: {
      type: 'info',
      message: '提示信息',
      description: '这是详细描述',
      showIcon: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'info',
        options: [
          { label: '信息', value: 'info' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '错误', value: 'error' },
        ],
        group: '基础',
      },
      {
        name: 'message',
        label: '标题',
        type: 'string',
        defaultValue: '提示信息',
        group: '基础',
      },
      {
        name: 'description',
        label: '描述',
        type: 'string',
        defaultValue: '这是详细描述',
        group: '基础',
      },
      {
        name: 'showIcon',
        label: '显示图标',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'closable',
        label: '可关闭',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'banner',
        label: '顶部公告',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  {
    type: 'Progress',
    name: '进度条',
    icon: <RocketOutlined />,
    category: 'feedback',
    defaultProps: {
      percent: 60,
      status: 'active',
      type: 'line',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'percent',
        label: '百分比',
        type: 'number',
        defaultValue: 60,
        min: 0,
        max: 100,
        group: '基础',
      },
      {
        name: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'line',
        options: [
          { label: '线条', value: 'line' },
          { label: '圆环', value: 'circle' },
          { label: '仪表盘', value: 'dashboard' },
        ],
        group: '基础',
      },
      {
        name: 'status',
        label: '状态',
        type: 'select',
        defaultValue: 'active',
        options: [
          { label: '活动', value: 'active' },
          { label: '成功', value: 'success' },
          { label: '异常', value: 'exception' },
        ],
        group: '基础',
      },
      {
        name: 'strokeWidth',
        label: '线宽',
        type: 'number',
        defaultValue: 6,
        min: 2,
        max: 20,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  {
    type: 'Spin',
    name: '加载中',
    icon: <LoadingOutlined />,
    category: 'feedback',
    defaultProps: {
      size: 'default',
      tip: '加载中...',
      spinning: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '小', value: 'small' },
          { label: '默认', value: 'default' },
          { label: '大', value: 'large' },
        ],
        group: '基础',
      },
      {
        name: 'tip',
        label: '提示文字',
        type: 'string',
        defaultValue: '加载中...',
        group: '基础',
      },
      {
        name: 'spinning',
        label: '是否加载',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  // ============ 更多展示组件 ============
  {
    type: 'Tag',
    name: '标签',
    icon: <TagOutlined />,
    category: 'display',
    defaultProps: {
      children: '标签',
      color: 'blue',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '内容',
        type: 'string',
        defaultValue: '标签',
        group: '基础',
      },
      {
        name: 'color',
        label: '颜色',
        type: 'select',
        defaultValue: 'blue',
        options: [
          { label: '蓝色', value: 'blue' },
          { label: '绿色', value: 'green' },
          { label: '红色', value: 'red' },
          { label: '橙色', value: 'orange' },
          { label: '紫色', value: 'purple' },
          { label: '青色', value: 'cyan' },
          { label: '默认', value: 'default' },
        ],
        group: '基础',
      },
      {
        name: 'closable',
        label: '可关闭',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'bordered',
        label: '有边框',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Badge',
    name: '徽标',
    icon: <AlertOutlined />,
    category: 'display',
    defaultProps: {
      count: 5,
      children: '消息',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'count',
        label: '数字',
        type: 'number',
        defaultValue: 5,
        min: 0,
        group: '基础',
      },
      {
        name: 'children',
        label: '内容',
        type: 'string',
        defaultValue: '消息',
        group: '基础',
      },
      {
        name: 'dot',
        label: '小红点',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'showZero',
        label: '显示零',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Avatar',
    name: '头像',
    icon: <AlertOutlined />,
    category: 'display',
    defaultProps: {
      size: 40,
      src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=1',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'src',
        label: '图片地址',
        type: 'string',
        defaultValue: 'https://api.dicebear.com/7.x/avataaars/svg?seed=1',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'number',
        defaultValue: 40,
        min: 20,
        max: 200,
        group: '基础',
      },
      {
        name: 'shape',
        label: '形状',
        type: 'select',
        defaultValue: 'circle',
        options: [
          { label: '圆形', value: 'circle' },
          { label: '方形', value: 'square' },
        ],
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Rate',
    name: '评分',
    icon: <AlertOutlined />,
    category: 'form',
    defaultProps: {
      count: 5,
      value: 3,
      allowHalf: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'count',
        label: '星星数',
        type: 'number',
        defaultValue: 5,
        min: 1,
        max: 10,
        group: '基础',
      },
      {
        name: 'value',
        label: '默认值',
        type: 'number',
        defaultValue: 3,
        min: 0,
        group: '基础',
      },
      {
        name: 'allowHalf',
        label: '允许半选',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Slider',
    name: '滑块',
    icon: <RocketOutlined />,
    category: 'form',
    defaultProps: {
      defaultValue: 30,
      min: 0,
      max: 100,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'defaultValue',
        label: '默认值',
        type: 'number',
        defaultValue: 30,
        group: '基础',
      },
      {
        name: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: 0,
        group: '基础',
      },
      {
        name: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: 100,
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'range',
        label: '双滑块',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'Radio',
    name: '单选框',
    icon: <CheckSquareOutlined />,
    category: 'form',
    defaultProps: {
      options: [
        { label: '选项A', value: 'a' },
        { label: '选项B', value: 'b' },
        { label: '选项C', value: 'c' },
      ],
      defaultValue: 'a',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'defaultValue',
        label: '默认值',
        type: 'string',
        defaultValue: 'a',
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Table',
    name: '表格',
    icon: <TableOutlined />,
    category: 'display',
    defaultProps: {
      columns: [
        { title: '姓名', dataIndex: 'name', key: 'name' },
        { title: '年龄', dataIndex: 'age', key: 'age' },
        { title: '地址', dataIndex: 'address', key: 'address' },
      ],
      dataSource: [
        { key: '1', name: '张三', age: 32, address: '北京市朝阳区' },
        { key: '2', name: '李四', age: 28, address: '上海市浦东新区' },
      ],
      size: 'middle',
      bordered: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'bordered',
        label: '显示边框',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'showHeader',
        label: '显示表头',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  // ============ 更多 Typography 组件 ============
  {
    type: 'Typography.Title',
    name: '标题',
    icon: <FileTextOutlined />,
    category: 'display',
    defaultProps: {
      children: '标题文字',
      level: 2,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: '标题文字',
        group: '基础',
      },
      {
        name: 'level',
        label: '标题级别',
        type: 'select',
        defaultValue: 2,
        options: [
          { label: 'H1', value: 1 },
          { label: 'H2', value: 2 },
          { label: 'H3', value: 3 },
          { label: 'H4', value: 4 },
          { label: 'H5', value: 5 },
        ],
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Typography.Paragraph',
    name: '段落',
    icon: <FileTextOutlined />,
    category: 'display',
    defaultProps: {
      children: '这是一段段落文字，可以包含多行内容。',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: '这是一段段落文字，可以包含多行内容。',
        group: '基础',
      },
      {
        name: 'ellipsis',
        label: '自动溢出省略',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  // ============ 更多表单组件 ============
  {
    type: 'InputNumber',
    name: '数字输入框',
    icon: <NumberOutlined />,
    category: 'form',
    defaultProps: {
      placeholder: '请输入数字',
      min: 0,
      max: 100,
      size: 'middle',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请输入数字',
        group: '基础',
      },
      {
        name: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: 0,
        group: '基础',
      },
      {
        name: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: 100,
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'TimePicker',
    name: '时间选择',
    icon: <ClockCircleOutlined />,
    category: 'form',
    defaultProps: {
      placeholder: '请选择时间',
      format: 'HH:mm:ss',
      size: 'middle',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请选择时间',
        group: '基础',
      },
      {
        name: 'format',
        label: '时间格式',
        type: 'string',
        defaultValue: 'HH:mm:ss',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  // ============ 布局组件 ============
  {
    type: 'Tabs',
    name: '标签页',
    icon: <SplitCellsOutlined />,
    category: 'layout',
    defaultProps: {
      items: [
        { key: '1', label: '标签一', children: '标签一内容' },
        { key: '2', label: '标签二', children: '标签二内容' },
        { key: '3', label: '标签三', children: '标签三内容' },
      ],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'line',
        options: [
          { label: '线条', value: 'line' },
          { label: '卡片', value: 'card' },
          { label: '可编辑', value: 'editable-card' },
        ],
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'tabPosition',
        label: '位置',
        type: 'select',
        defaultValue: 'top',
        options: [
          { label: '顶部', value: 'top' },
          { label: '底部', value: 'bottom' },
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
        ],
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: '100%', height: 150 },
  },

  {
    type: 'Collapse',
    name: '折叠面板',
    icon: <DownOutlined />,
    category: 'layout',
    defaultProps: {
      items: [
        { key: '1', label: '面板一', children: '面板一内容' },
        { key: '2', label: '面板二', children: '面板二内容' },
      ],
      accordion: false,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'accordion',
        label: '手风琴模式',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'ghost',
        label: '幽灵模式',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: '100%', height: 'auto' },
  },

  // ============ 表单容器组件 ============
  {
    type: 'Form',
    name: '表单',
    icon: <ProfileOutlined />,
    category: 'form',
    defaultProps: {
      layout: 'vertical',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'layout',
        label: '布局方式',
        type: 'select',
        defaultValue: 'vertical',
        options: [
          { label: '垂直', value: 'vertical' },
          { label: '水平', value: 'horizontal' },
          { label: '行内', value: 'inline' },
        ],
        group: '基础',
      },
      {
        name: 'labelCol',
        label: '标签宽度',
        type: 'number',
        defaultValue: 6,
        min: 1,
        max: 24,
        group: '基础',
      },
      {
        name: 'wrapperCol',
        label: '控件宽度',
        type: 'number',
        defaultValue: 18,
        min: 1,
        max: 24,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: '100%', height: 'auto' },
  },

  {
    type: 'Form.Item',
    name: '表单项',
    icon: <FormOutlined />,
    category: 'form',
    defaultProps: {
      label: '表单项',
      name: 'field',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'label',
        label: '标签',
        type: 'string',
        defaultValue: '表单项',
        group: '基础',
      },
      {
        name: 'name',
        label: '字段名',
        type: 'string',
        defaultValue: 'field',
        group: '基础',
      },
      {
        name: 'required',
        label: '必填',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'rules',
        label: '验证规则',
        type: 'string',
        defaultValue: '',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: '100%', height: 'auto' },
  },

  // ============ 导航组件 ============
  {
    type: 'Breadcrumb',
    name: '面包屑',
    icon: <UnorderedListOutlined />,
    category: 'layout',
    defaultProps: {
      items: [
        { title: '首页' },
        { title: '应用中心' },
        { title: '应用列表' },
      ],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'separator',
        label: '分隔符',
        type: 'string',
        defaultValue: '/',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Steps',
    name: '步骤条',
    icon: <UnorderedListOutlined />,
    category: 'layout',
    defaultProps: {
      current: 1,
      items: [
        { title: '已完成', description: '这是描述' },
        { title: '进行中', description: '这是描述' },
        { title: '待处理', description: '这是描述' },
      ],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'current',
        label: '当前步骤',
        type: 'number',
        defaultValue: 1,
        min: 0,
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'direction',
        label: '方向',
        type: 'select',
        defaultValue: 'horizontal',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  // ============ 更多展示组件 ============
  {
    type: 'Empty',
    name: '空状态',
    icon: <AlertOutlined />,
    category: 'display',
    defaultProps: {
      description: '暂无数据',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'description',
        label: '描述文字',
        type: 'string',
        defaultValue: '暂无数据',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Result',
    name: '结果页',
    icon: <RocketOutlined />,
    category: 'display',
    defaultProps: {
      status: 'success',
      title: '操作成功',
      subTitle: '这是一条成功提示信息',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'status',
        label: '状态',
        type: 'select',
        defaultValue: 'success',
        options: [
          { label: '成功', value: 'success' },
          { label: '错误', value: 'error' },
          { label: '信息', value: 'info' },
          { label: '警告', value: 'warning' },
          { label: '404', value: '404' },
          { label: '403', value: '403' },
          { label: '500', value: '500' },
        ],
        group: '基础',
      },
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '操作成功',
        group: '基础',
      },
      {
        name: 'subTitle',
        label: '副标题',
        type: 'string',
        defaultValue: '这是一条成功提示信息',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  {
    type: 'Skeleton',
    name: '骨架屏',
    icon: <LoadingOutlined />,
    category: 'display',
    defaultProps: {
      active: true,
      paragraph: { rows: 4 },
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'active',
        label: '动画效果',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  {
    type: 'Timeline',
    name: '时间轴',
    icon: <ClockCircleOutlined />,
    category: 'display',
    defaultProps: {
      items: [
        { children: '创建 2015-09-01', color: 'green' },
        { children: '初审 2015-09-01', color: 'blue' },
        { children: '二审 2015-09-01', color: 'red' },
        { children: '终审 2015-09-01' },
      ],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'mode',
        label: '模式',
        type: 'select',
        defaultValue: 'left',
        options: [
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
          { label: '交替', value: 'alternate' },
        ],
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Tree',
    name: '树形控件',
    icon: <UnorderedListOutlined />,
    category: 'display',
    defaultProps: {
      treeData: [
        { title: '节点一', key: '0-0', children: [{ title: '子节点', key: '0-0-0' }] },
        { title: '节点二', key: '0-1' },
      ],
      defaultExpandAll: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'showLine',
        label: '显示连接线',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'defaultExpandAll',
        label: '默认展开',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'List',
    name: '列表',
    icon: <UnorderedListOutlined />,
    category: 'display',
    defaultProps: {
      dataSource: ['项目一', '项目二', '项目三'],
      renderItem: (item: string) => item,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
          { label: '大', value: 'large' },
        ],
        group: '基础',
      },
      {
        name: 'bordered',
        label: '显示边框',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: '100%', height: 'auto' },
  },

  // ============ 数据录入扩展 ============
  {
    type: 'Cascader',
    name: '级联选择',
    icon: <DownOutlined />,
    category: 'form',
    defaultProps: {
      placeholder: '请选择',
      options: [
        {
          value: 'zhejiang',
          label: '浙江',
          children: [{ value: 'hangzhou', label: '杭州' }],
        },
        {
          value: 'jiangsu',
          label: '江苏',
          children: [{ value: 'nanjing', label: '南京' }],
        },
      ],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请选择',
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'Transfer',
    name: '穿梭框',
    icon: <SplitCellsOutlined />,
    category: 'form',
    defaultProps: {
      dataSource: [
        { key: '1', title: '选项一' },
        { key: '2', title: '选项二' },
        { key: '3', title: '选项三' },
      ],
      targetKeys: ['1'],
      titles: ['源列表', '目标列表'],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'showSearch',
        label: '显示搜索',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 500, height: 'auto' },
  },

  // ============ 其他组件 ============
  {
    type: 'Segmented',
    name: '分段控制器',
    icon: <SplitCellsOutlined />,
    category: 'basic',
    defaultProps: {
      options: ['日', '周', '月', '季', '年'],
      value: '日',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'block',
        label: '宽度撑满',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Pagination',
    name: '分页',
    icon: <UnorderedListOutlined />,
    category: 'display',
    defaultProps: {
      total: 100,
      showSizeChanger: true,
      showQuickJumper: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'total',
        label: '总数',
        type: 'number',
        defaultValue: 100,
        group: '基础',
      },
      {
        name: 'pageSize',
        label: '每页条数',
        type: 'select',
        defaultValue: 10,
        options: [
          { label: '10条', value: 10 },
          { label: '20条', value: 20 },
          { label: '50条', value: 50 },
          { label: '100条', value: 100 },
        ],
        group: '基础',
      },
      {
        name: 'showSizeChanger',
        label: '显示条数选择',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Calendar',
    name: '日历',
    icon: <CalendarOutlined />,
    category: 'display',
    defaultProps: {},
    defaultStyle: {},
    propSchema: [],
    allowChildren: false,
    defaultSize: { width: 300, height: 300 },
  },

  {
    type: 'QRCode',
    name: '二维码',
    icon: <CodeOutlined />,
    category: 'display',
    defaultProps: {
      value: 'https://ant.design/',
      size: 128,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'value',
        label: '二维码内容',
        type: 'string',
        defaultValue: 'https://ant.design/',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'number',
        defaultValue: 128,
        min: 32,
        max: 512,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 128, height: 128 },
  },

  {
    type: 'Popover',
    name: '气泡卡片',
    icon: <AlertOutlined />,
    category: 'display',
    defaultProps: {
      title: '标题',
      content: '这是气泡卡片的内容',
      trigger: 'click',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '标题',
        group: '基础',
      },
      {
        name: 'trigger',
        label: '触发方式',
        type: 'select',
        defaultValue: 'click',
        options: [
          { label: '点击', value: 'click' },
          { label: '悬停', value: 'hover' },
        ],
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Tooltip',
    name: '文字提示',
    icon: <InfoCircleOutlined />,
    category: 'display',
    defaultProps: {
      title: '提示文字',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '提示内容',
        type: 'string',
        defaultValue: '提示文字',
        group: '基础',
      },
      {
        name: 'placement',
        label: '位置',
        type: 'select',
        defaultValue: 'top',
        options: [
          { label: '上方', value: 'top' },
          { label: '下方', value: 'bottom' },
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
        ],
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Watermark',
    name: '水印',
    icon: <SettingOutlined />,
    category: 'layout',
    defaultProps: {
      content: 'Ant Design',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'content',
        label: '水印内容',
        type: 'string',
        defaultValue: 'Ant Design',
        group: '基础',
      },
      {
        name: 'fontSize',
        label: '字体大小',
        type: 'number',
        defaultValue: 16,
        min: 8,
        max: 32,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: '100%', height: 200 },
  },

  // ============ 原生HTML元素 ============
  {
    type: 'HTMLElement.div',
    name: 'div',
    icon: <BorderOutlined />,
    category: 'html',
    defaultProps: {},
    defaultStyle: {
      minWidth: 100,
      minHeight: 60,
      backgroundColor: '#f5f5f5',
    },
    propSchema: [],
    allowChildren: true,
    defaultSize: { width: 200, height: 100 },
  },

  {
    type: 'HTMLElement.span',
    name: 'span',
    icon: <FileTextOutlined />,
    category: 'html',
    defaultProps: {
      children: 'span 文本',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: 'span 文本',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.p',
    name: 'p',
    icon: <FileTextOutlined />,
    category: 'html',
    defaultProps: {
      children: '这是一段段落文本',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: '这是一段段落文本',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.h1',
    name: 'h1',
    icon: <FileTextOutlined />,
    category: 'html',
    defaultProps: {
      children: '标题 1',
    },
    defaultStyle: {
      fontSize: 32,
      fontWeight: 'bold',
    },
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: '标题 1',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.h2',
    name: 'h2',
    icon: <FileTextOutlined />,
    category: 'html',
    defaultProps: {
      children: '标题 2',
    },
    defaultStyle: {
      fontSize: 28,
      fontWeight: 'bold',
    },
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: '标题 2',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.h3',
    name: 'h3',
    icon: <FileTextOutlined />,
    category: 'html',
    defaultProps: {
      children: '标题 3',
    },
    defaultStyle: {
      fontSize: 24,
      fontWeight: 'bold',
    },
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: '标题 3',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.img',
    name: 'img',
    icon: <PictureOutlined />,
    category: 'html',
    defaultProps: {
      src: 'https://via.placeholder.com/200x150',
      alt: '图片',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'src',
        label: '图片地址',
        type: 'string',
        defaultValue: 'https://via.placeholder.com/200x150',
        group: '基础',
      },
      {
        name: 'alt',
        label: '替代文本',
        type: 'string',
        defaultValue: '图片',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 150 },
  },

  {
    type: 'HTMLElement.a',
    name: 'a',
    icon: <FileTextOutlined />,
    category: 'html',
    defaultProps: {
      href: 'https://example.com',
      children: '链接文字',
      target: '_blank',
    },
    defaultStyle: {
      color: '#1890ff',
      textDecoration: 'underline',
    },
    propSchema: [
      {
        name: 'children',
        label: '链接文字',
        type: 'string',
        defaultValue: '链接文字',
        group: '基础',
      },
      {
        name: 'href',
        label: '链接地址',
        type: 'string',
        defaultValue: 'https://example.com',
        group: '基础',
      },
      {
        name: 'target',
        label: '打开方式',
        type: 'select',
        defaultValue: '_blank',
        options: [
          { label: '新窗口', value: '_blank' },
          { label: '当前窗口', value: '_self' },
        ],
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.ul',
    name: 'ul',
    icon: <UnorderedListOutlined />,
    category: 'html',
    defaultProps: {
      items: ['列表项 1', '列表项 2', '列表项 3'],
    },
    defaultStyle: {},
    propSchema: [],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.ol',
    name: 'ol',
    icon: <OrderedListOutlined />,
    category: 'html',
    defaultProps: {
      items: ['列表项 1', '列表项 2', '列表项 3'],
    },
    defaultStyle: {},
    propSchema: [],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.li',
    name: 'li',
    icon: <LineOutlined />,
    category: 'html',
    defaultProps: {
      children: '列表项',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: '列表项',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.button',
    name: 'button',
    icon: <AppstoreOutlined />,
    category: 'html',
    defaultProps: {
      children: '按钮',
    },
    defaultStyle: {
      padding: '8px 16px',
      backgroundColor: '#1890ff',
      color: '#fff',
      border: 'none',
      borderRadius: 4,
      cursor: 'pointer',
    },
    propSchema: [
      {
        name: 'children',
        label: '按钮文字',
        type: 'string',
        defaultValue: '按钮',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.input',
    name: 'input',
    icon: <FormOutlined />,
    category: 'html',
    defaultProps: {
      type: 'text',
      placeholder: '请输入',
    },
    defaultStyle: {
      padding: '8px 12px',
      border: '1px solid #d9d9d9',
      borderRadius: 4,
    },
    propSchema: [
      {
        name: 'type',
        label: '输入类型',
        type: 'select',
        defaultValue: 'text',
        options: [
          { label: '文本', value: 'text' },
          { label: '密码', value: 'password' },
          { label: '邮箱', value: 'email' },
          { label: '数字', value: 'number' },
        ],
        group: '基础',
      },
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请输入',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'HTMLElement.textarea',
    name: 'textarea',
    icon: <FormOutlined />,
    category: 'html',
    defaultProps: {
      placeholder: '请输入',
      rows: 4,
    },
    defaultStyle: {
      padding: '8px 12px',
      border: '1px solid #d9d9d9',
      borderRadius: 4,
    },
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请输入',
        group: '基础',
      },
      {
        name: 'rows',
        label: '行数',
        type: 'number',
        defaultValue: 4,
        min: 2,
        max: 10,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 300, height: 100 },
  },

  {
    type: 'HTMLElement.select',
    name: 'select',
    icon: <BorderOutlined />,
    category: 'html',
    defaultProps: {
      options: [
        { label: '选项 1', value: '1' },
        { label: '选项 2', value: '2' },
      ],
    },
    defaultStyle: {
      padding: '8px 12px',
      border: '1px solid #d9d9d9',
      borderRadius: 4,
    },
    propSchema: [],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'HTMLElement.form',
    name: 'form',
    icon: <ProfileOutlined />,
    category: 'html',
    defaultProps: {},
    defaultStyle: {
      padding: 16,
      border: '1px solid #d9d9d9',
      borderRadius: 4,
    },
    propSchema: [],
    allowChildren: true,
    defaultSize: { width: 300, height: 200 },
  },

  {
    type: 'HTMLElement.table',
    name: 'table',
    icon: <TableOutlined />,
    category: 'html',
    defaultProps: {},
    defaultStyle: {
      borderCollapse: 'collapse',
    },
    propSchema: [],
    allowChildren: true,
    defaultSize: { width: 300, height: 150 },
  },

  {
    type: 'HTMLElement.code',
    name: 'code',
    icon: <CodeOutlined />,
    category: 'html',
    defaultProps: {
      children: 'console.log("Hello")',
    },
    defaultStyle: {
      fontFamily: 'monospace',
      backgroundColor: '#f5f5f5',
      padding: '4px 8px',
      borderRadius: 4,
    },
    propSchema: [
      {
        name: 'children',
        label: '代码内容',
        type: 'string',
        defaultValue: 'console.log("Hello")',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'HTMLElement.pre',
    name: 'pre',
    icon: <CodeOutlined />,
    category: 'html',
    defaultProps: {
      children: '// 代码块\nfunction hello() {\n  console.log("Hello");\n}',
    },
    defaultStyle: {
      fontFamily: 'monospace',
      backgroundColor: '#f5f5f5',
      padding: 16,
      borderRadius: 4,
      whiteSpace: 'pre-wrap',
    },
    propSchema: [
      {
        name: 'children',
        label: '代码内容',
        type: 'string',
        defaultValue: '// 代码块\nfunction hello() {\n  console.log("Hello");\n}',
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 300, height: 120 },
  },
];
