import { ComponentConfig, CategoryConfig } from '@/types';
import {
  AppstoreOutlined,
  BorderOutlined,
  CheckSquareOutlined,
  FormOutlined,
  FileTextOutlined,
  PictureOutlined,
  SyncOutlined,
  CalendarOutlined,
  UploadOutlined,
  CreditCardOutlined,
  SplitCellsOutlined,
  ProfileOutlined,
  FundOutlined,
  AlertOutlined,
  MessageOutlined,
  NotificationOutlined,
  LoadingOutlined,
  TagOutlined,
  TableOutlined,
  MenuFoldOutlined,
  InfoCircleOutlined,
  RocketOutlined,
  StarOutlined,
} from '@ant-design/icons';

/**
 * 组件分类配置
 */
export const CATEGORIES: CategoryConfig[] = [
  { key: 'basic', name: '基础组件', order: 1 },
  { key: 'form', name: '表单组件', order: 2 },
  { key: 'layout', name: '布局组件', order: 3 },
  { key: 'display', name: '展示组件', order: 4 },
  { key: 'feedback', name: '反馈组件', order: 5 },
];

/**
 * 预设组件配置
 */
export const PRESET_COMPONENTS: ComponentConfig[] = [
  // ============ 基础组件 ============
  {
    type: 'Button',
    name: '按钮',
    icon: <AppstoreOutlined />,
    category: 'basic',
    defaultProps: {
      children: '按钮',
      type: 'primary',
      size: 'middle',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '按钮文字',
        type: 'string',
        defaultValue: '按钮',
        group: '基础',
      },
      {
        name: 'type',
        label: '按钮类型',
        type: 'select',
        defaultValue: 'primary',
        options: [
          { label: '主要按钮', value: 'primary' },
          { label: '默认按钮', value: 'default' },
          { label: '虚线按钮', value: 'dashed' },
          { label: '文字按钮', value: 'text' },
          { label: '链接按钮', value: 'link' },
        ],
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'block',
        label: '宽度撑满',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Input',
    name: '输入框',
    icon: <FormOutlined />,
    category: 'basic',
    defaultProps: {
      placeholder: '请输入',
      size: 'middle',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请输入',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'allowClear',
        label: '允许清除',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'Select',
    name: '下拉选择',
    icon: <BorderOutlined />,
    category: 'basic',
    defaultProps: {
      placeholder: '请选择',
      size: 'middle',
      options: [
        { label: '选项一', value: '1' },
        { label: '选项二', value: '2' },
      ],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请选择',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'allowClear',
        label: '允许清除',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  // ============ 表单组件 ============
  {
    type: 'Checkbox',
    name: '复选框',
    icon: <CheckSquareOutlined />,
    category: 'form',
    defaultProps: {
      children: '复选框',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '标签文字',
        type: 'string',
        defaultValue: '复选框',
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Switch',
    name: '开关',
    icon: <SyncOutlined />,
    category: 'form',
    defaultProps: {
      checkedChildren: '开',
      unCheckedChildren: '关',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'checkedChildren',
        label: '选中文字',
        type: 'string',
        defaultValue: '开',
        group: '基础',
      },
      {
        name: 'unCheckedChildren',
        label: '未选中文字',
        type: 'string',
        defaultValue: '关',
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'DatePicker',
    name: '日期选择',
    icon: <CalendarOutlined />,
    category: 'form',
    defaultProps: {
      placeholder: '请选择日期',
      size: 'middle',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'placeholder',
        label: '占位文本',
        type: 'string',
        defaultValue: '请选择日期',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'Upload',
    name: '上传',
    icon: <UploadOutlined />,
    category: 'form',
    defaultProps: {},
    defaultStyle: {},
    propSchema: [
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  // ============ 布局组件 ============
  {
    type: 'Card',
    name: '卡片',
    icon: <CreditCardOutlined />,
    category: 'layout',
    defaultProps: {
      title: '卡片标题',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '卡片标题',
        group: '基础',
      },
      {
        name: 'bordered',
        label: '显示边框',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'hoverable',
        label: '悬停效果',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 300, height: 200 },
  },

  {
    type: 'Divider',
    name: '分割线',
    icon: <SplitCellsOutlined />,
    category: 'layout',
    defaultProps: {
      orientation: 'center',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'orientation',
        label: '文字位置',
        type: 'select',
        defaultValue: 'center',
        options: [
          { label: '居左', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '居右', value: 'right' },
        ],
        group: '基础',
      },
      {
        name: 'dashed',
        label: '虚线',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  // ============ 展示组件 ============
  {
    type: 'Typography.Text',
    name: '文本',
    icon: <FileTextOutlined />,
    category: 'display',
    defaultProps: {
      children: '这是一段文本',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '文本内容',
        type: 'string',
        defaultValue: '这是一段文本',
        group: '基础',
      },
      {
        name: 'type',
        label: '文本类型',
        type: 'select',
        defaultValue: undefined,
        options: [
          { label: '默认', value: undefined },
          { label: '次要', value: 'secondary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
        ],
        group: '基础',
      },
      {
        name: 'bold',
        label: '加粗',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Image',
    name: '图片',
    icon: <PictureOutlined />,
    category: 'display',
    defaultProps: {
      src: 'https://via.placeholder.com/200x150',
      alt: '图片',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'src',
        label: '图片地址',
        type: 'string',
        defaultValue: 'https://via.placeholder.com/200x150',
        group: '基础',
      },
      {
        name: 'alt',
        label: '替代文本',
        type: 'string',
        defaultValue: '图片',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 150 },
  },

  {
    type: 'Statistic',
    name: '统计数值',
    icon: <FundOutlined />,
    category: 'display',
    defaultProps: {
      title: '活跃用户',
      value: 112893,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '活跃用户',
        group: '基础',
      },
      {
        name: 'value',
        label: '数值',
        type: 'number',
        defaultValue: 112893,
        group: '基础',
      },
      {
        name: 'prefix',
        label: '前缀',
        type: 'string',
        defaultValue: '',
        group: '基础',
      },
      {
        name: 'suffix',
        label: '后缀',
        type: 'string',
        defaultValue: '',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Descriptions',
    name: '描述列表',
    icon: <ProfileOutlined />,
    category: 'display',
    defaultProps: {
      title: '描述列表',
      items: [
        { label: '姓名', children: '张三' },
        { label: '年龄', children: '25' },
        { label: '地址', children: '北京市朝阳区' },
      ],
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '描述列表',
        group: '基础',
      },
      {
        name: 'bordered',
        label: '显示边框',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'column',
        label: '列数',
        type: 'number',
        defaultValue: 3,
        min: 1,
        max: 4,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  // ============ 反馈组件 ============
  {
    type: 'Modal',
    name: '对话框',
    icon: <AlertOutlined />,
    category: 'feedback',
    defaultProps: {
      title: '对话框标题',
      open: true,
      children: '对话框内容',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '对话框标题',
        group: '基础',
      },
      {
        name: 'open',
        label: '是否显示',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'width',
        label: '宽度',
        type: 'number',
        defaultValue: 520,
        group: '基础',
      },
      {
        name: 'centered',
        label: '垂直居中',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 520, height: 'auto' },
  },

  {
    type: 'Drawer',
    name: '抽屉',
    icon: <MenuFoldOutlined />,
    category: 'feedback',
    defaultProps: {
      title: '抽屉标题',
      open: true,
      placement: 'right',
      width: 378,
      children: '抽屉内容',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'title',
        label: '标题',
        type: 'string',
        defaultValue: '抽屉标题',
        group: '基础',
      },
      {
        name: 'open',
        label: '是否显示',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'placement',
        label: '方向',
        type: 'select',
        defaultValue: 'right',
        options: [
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
          { label: '顶部', value: 'top' },
          { label: '底部', value: 'bottom' },
        ],
        group: '基础',
      },
      {
        name: 'width',
        label: '宽度',
        type: 'number',
        defaultValue: 378,
        group: '基础',
      },
    ],
    allowChildren: true,
    defaultSize: { width: 378, height: 300 },
  },

  {
    type: 'Message',
    name: '全局提示',
    icon: <MessageOutlined />,
    category: 'feedback',
    defaultProps: {
      type: 'info',
      content: '这是一条提示信息',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'info',
        options: [
          { label: '信息', value: 'info' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '错误', value: 'error' },
          { label: '加载中', value: 'loading' },
        ],
        group: '基础',
      },
      {
        name: 'content',
        label: '内容',
        type: 'string',
        defaultValue: '这是一条提示信息',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Notification',
    name: '通知提醒',
    icon: <NotificationOutlined />,
    category: 'feedback',
    defaultProps: {
      type: 'info',
      message: '通知标题',
      description: '这是通知的详细描述内容',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'info',
        options: [
          { label: '信息', value: 'info' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '错误', value: 'error' },
        ],
        group: '基础',
      },
      {
        name: 'message',
        label: '标题',
        type: 'string',
        defaultValue: '通知标题',
        group: '基础',
      },
      {
        name: 'description',
        label: '描述',
        type: 'string',
        defaultValue: '这是通知的详细描述内容',
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 384, height: 'auto' },
  },

  {
    type: 'Alert',
    name: '警告提示',
    icon: <InfoCircleOutlined />,
    category: 'feedback',
    defaultProps: {
      type: 'info',
      message: '提示信息',
      description: '这是详细描述',
      showIcon: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'info',
        options: [
          { label: '信息', value: 'info' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '错误', value: 'error' },
        ],
        group: '基础',
      },
      {
        name: 'message',
        label: '标题',
        type: 'string',
        defaultValue: '提示信息',
        group: '基础',
      },
      {
        name: 'description',
        label: '描述',
        type: 'string',
        defaultValue: '这是详细描述',
        group: '基础',
      },
      {
        name: 'showIcon',
        label: '显示图标',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'closable',
        label: '可关闭',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'banner',
        label: '顶部公告',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  {
    type: 'Progress',
    name: '进度条',
    icon: <RocketOutlined />,
    category: 'feedback',
    defaultProps: {
      percent: 60,
      status: 'active',
      type: 'line',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'percent',
        label: '百分比',
        type: 'number',
        defaultValue: 60,
        min: 0,
        max: 100,
        group: '基础',
      },
      {
        name: 'type',
        label: '类型',
        type: 'select',
        defaultValue: 'line',
        options: [
          { label: '线条', value: 'line' },
          { label: '圆环', value: 'circle' },
          { label: '仪表盘', value: 'dashboard' },
        ],
        group: '基础',
      },
      {
        name: 'status',
        label: '状态',
        type: 'select',
        defaultValue: 'active',
        options: [
          { label: '活动', value: 'active' },
          { label: '成功', value: 'success' },
          { label: '异常', value: 'exception' },
        ],
        group: '基础',
      },
      {
        name: 'strokeWidth',
        label: '线宽',
        type: 'number',
        defaultValue: 6,
        min: 2,
        max: 20,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },

  {
    type: 'Spin',
    name: '加载中',
    icon: <LoadingOutlined />,
    category: 'feedback',
    defaultProps: {
      size: 'default',
      tip: '加载中...',
      spinning: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'default',
        options: [
          { label: '小', value: 'small' },
          { label: '默认', value: 'default' },
          { label: '大', value: 'large' },
        ],
        group: '基础',
      },
      {
        name: 'tip',
        label: '提示文字',
        type: 'string',
        defaultValue: '加载中...',
        group: '基础',
      },
      {
        name: 'spinning',
        label: '是否加载',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  // ============ 更多展示组件 ============
  {
    type: 'Tag',
    name: '标签',
    icon: <TagOutlined />,
    category: 'display',
    defaultProps: {
      children: '标签',
      color: 'blue',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'children',
        label: '内容',
        type: 'string',
        defaultValue: '标签',
        group: '基础',
      },
      {
        name: 'color',
        label: '颜色',
        type: 'select',
        defaultValue: 'blue',
        options: [
          { label: '蓝色', value: 'blue' },
          { label: '绿色', value: 'green' },
          { label: '红色', value: 'red' },
          { label: '橙色', value: 'orange' },
          { label: '紫色', value: 'purple' },
          { label: '青色', value: 'cyan' },
          { label: '默认', value: 'default' },
        ],
        group: '基础',
      },
      {
        name: 'closable',
        label: '可关闭',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'bordered',
        label: '有边框',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Badge',
    name: '徽标',
    icon: <AlertOutlined />,
    category: 'display',
    defaultProps: {
      count: 5,
      children: '消息',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'count',
        label: '数字',
        type: 'number',
        defaultValue: 5,
        min: 0,
        group: '基础',
      },
      {
        name: 'children',
        label: '内容',
        type: 'string',
        defaultValue: '消息',
        group: '基础',
      },
      {
        name: 'dot',
        label: '小红点',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'showZero',
        label: '显示零',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Avatar',
    name: '头像',
    icon: <AlertOutlined />,
    category: 'display',
    defaultProps: {
      size: 40,
      src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=1',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'src',
        label: '图片地址',
        type: 'string',
        defaultValue: 'https://api.dicebear.com/7.x/avataaars/svg?seed=1',
        group: '基础',
      },
      {
        name: 'size',
        label: '尺寸',
        type: 'number',
        defaultValue: 40,
        min: 20,
        max: 200,
        group: '基础',
      },
      {
        name: 'shape',
        label: '形状',
        type: 'select',
        defaultValue: 'circle',
        options: [
          { label: '圆形', value: 'circle' },
          { label: '方形', value: 'square' },
        ],
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Rate',
    name: '评分',
    icon: <AlertOutlined />,
    category: 'form',
    defaultProps: {
      count: 5,
      value: 3,
      allowHalf: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'count',
        label: '星星数',
        type: 'number',
        defaultValue: 5,
        min: 1,
        max: 10,
        group: '基础',
      },
      {
        name: 'value',
        label: '默认值',
        type: 'number',
        defaultValue: 3,
        min: 0,
        group: '基础',
      },
      {
        name: 'allowHalf',
        label: '允许半选',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Slider',
    name: '滑块',
    icon: <RocketOutlined />,
    category: 'form',
    defaultProps: {
      defaultValue: 30,
      min: 0,
      max: 100,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'defaultValue',
        label: '默认值',
        type: 'number',
        defaultValue: 30,
        group: '基础',
      },
      {
        name: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: 0,
        group: '基础',
      },
      {
        name: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: 100,
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
      {
        name: 'range',
        label: '双滑块',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 200, height: 'auto' },
  },

  {
    type: 'Radio',
    name: '单选框',
    icon: <CheckSquareOutlined />,
    category: 'form',
    defaultProps: {
      options: [
        { label: '选项A', value: 'a' },
        { label: '选项B', value: 'b' },
        { label: '选项C', value: 'c' },
      ],
      defaultValue: 'a',
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'defaultValue',
        label: '默认值',
        type: 'string',
        defaultValue: 'a',
        group: '基础',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: 'boolean',
        defaultValue: false,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: 'auto', height: 'auto' },
  },

  {
    type: 'Table',
    name: '表格',
    icon: <TableOutlined />,
    category: 'display',
    defaultProps: {
      columns: [
        { title: '姓名', dataIndex: 'name', key: 'name' },
        { title: '年龄', dataIndex: 'age', key: 'age' },
        { title: '地址', dataIndex: 'address', key: 'address' },
      ],
      dataSource: [
        { key: '1', name: '张三', age: 32, address: '北京市朝阳区' },
        { key: '2', name: '李四', age: 28, address: '上海市浦东新区' },
      ],
      size: 'middle',
      bordered: true,
    },
    defaultStyle: {},
    propSchema: [
      {
        name: 'size',
        label: '尺寸',
        type: 'select',
        defaultValue: 'middle',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'middle' },
          { label: '小', value: 'small' },
        ],
        group: '基础',
      },
      {
        name: 'bordered',
        label: '显示边框',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
      {
        name: 'showHeader',
        label: '显示表头',
        type: 'boolean',
        defaultValue: true,
        group: '基础',
      },
    ],
    allowChildren: false,
    defaultSize: { width: '100%', height: 'auto' },
  },
];
